```{r overtime, fig.cap="SGLT2 overtime"}

ggplot(
  data = overtime,
  aes(x = year, y = percent)
) +
  geom_line(color = kicols[1], size = 2) +
  geom_point(size = 2) +
  theme_minimal() +
  scale_x_continuous(labels = overtime$year, breaks = overtime$year, minor_breaks = overtime$year) +
  scale_y_continuous(labels = seq(0, 12, 2), breaks = seq(0, 12, 2), minor_breaks = seq(0, 12, 2)) +
  xlab("Year") +
  ylab("% of patients")
```

```{r overtimetab}
overtimetab <- overtime %>%
  mutate(percent = dF(percent, 1))
mykable(overtimetab, scale_down = FALSE, caption = "SGLT2 overtime (exact percent from Fig)")
```

```{r tabsglt2end, cache=cacheon}

sglt2end <- lm2018 %>% 
  count(ddr_sglt2_end) %>% 
  mutate(pro = dF(n/ sum(n) * 100, 1),
         np = paste0(n, " (", pro, "%)")) %>%
  select(ddr_sglt2_end, np)

colnames(sglt2end) <- c("Last SGLT2 dispension during 2018", "n (%)")

mykable(sglt2end,
  caption = "Last dispension during 2018 (same pop as in graph).", 
  scale_down = FALSE
)
```